/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./src/components/Categories.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    Products: typeof import('./src/components/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubCategories: typeof import('./src/components/SubCategories.vue')['default']
  }
}
